---
functional:
  - Пользователь должен иметь возможность регистрации через электронную почту 
  - Невозможно повторно зарегистрироваться по email
  - Нельзя зарегистрироваться по несуществующему email
  - Пользователь должен иметь возможность авторизации через GitHub
  - Пользователь должен иметь возможность авторизации по email и паролю
  - Пользователь должен иметь возможность создавать игру, выбирая необходимые ему параметры это с кем игра, вид задачи, время, сложность
  - Пользователь должен иметь возможность видеть код соперника в реальном времени
  - Пользователь должен иметь возможность просматривать свой рейтинг и таблицу рейтинга других игроков
  - Пользователь должен иметь возможность писать в чат сопернику и зрителям
  - Пользователь должен иметь возможность просматривать свой рейтинг и таблицу рейтинга других игроков
 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Сайт должен иметь русскую локализацию
  - Сайт должен иметь возможность выбора тёмной темы
  - Возможность обратной связи
  - У пользователя должна быть возможность изменять свой пароль
